language: node_js
cache:
  yarn: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: 4
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   node_js: 5
    - os: linux
      dist: trusty
      sudo: false
      node_js: 6
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   node_js: 7
    - os: linux
      dist: trusty
      sudo: false
      node_js: 8
    - os: osx
      osx_image: xcode8
      node_js: 4
before_install:
  - npm install -g yarn
