sudo: false
language: node_js
matrix:
  include:
    - os: linux
      node_js: 10
    - os: linux
      node_js: 8
    - os: linux
      node_js: 6
    - os: osx
      osx_image: xcode10
      node_js: 6
script:
  - yarn test
