os: Visual Studio 2017
platform: x64
environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off
deploy: off
