os: Visual Studio 2015
platform: x64
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

build: off
deploy: off
